version: "3"

services:
  rcon:
    image: forewing/webrcon-server
    networks:
      - traefik-public

    ## `csgo` is the game server's service name
    ##command: "-addr csgo:27015"

    ## if you prefer using config file, comment out previous `command:` line,
    ## create config.json and uncomment next few lines

    command: "-conf /app/config.json"
    volumes:
      - /<path to config file>/config.json:/app/config.json
    networks:
     - <trafik-public-network-name>
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.webrcon-https.rule: Host(`<hostname>`)
        traefik.http.routers.webrcon-https.tls.certresolver: cloudflare
        traefik.http.routers.webrcon-http.entrypoints: http
        traefik.http.routers.webrcon-https.tls: 'true'
        traefik.constraint-label: traefik-public
        traefik.http.services.webrcon.loadbalancer.server.port: '8080'
        traefik.http.routers.webrcon-http.middlewares: https-redirect
        traefik.http.routers.webrcon-http.rule: Host(`<hostname>`)
        traefik.http.routers.webrcon-https.entrypoints: https
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
networks:
  <trafik-public-network-name>:
    external: true
