version: "3"

services:
  rcon:
    image: forewing/webrcon-server
    ports:
      - 8081:8080
    restart: unless-stopped

    ## `csgo` is the game server's service name
    ##command: "-addr csgo:27015"

    ## if you prefer using config file, comment out previous `command:` line,
    ## create config.json and uncomment next few lines

    command: "-conf /app/config.json"
    volumes:
      - /<path to config file>/config.json:/app/config.json
